# Generated by Django 3.1.3 on 2023-10-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='lesson',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='enrollment_id',
            new_name='enrollment',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='choice_id',
        ),
        migrations.AddField(
            model_name='submission',
            name='choices',
            field=models.ManyToManyField(blank=True, to='onlinecourse.Choice'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='grade',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(default='Question', max_length=200),
        ),
    ]
